NUMPY

In [3]:
import numpy as np

In [4]:
arr=np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [5]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [6]:
np.ones((3,2))

array([[1., 1.],
       [1., 1.],
       [1., 1.]])

In [7]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [10]:
np.arange(1,10,2)   #

array([1, 3, 5, 7, 9])

In [12]:
np.linspace(0,1,5)   #Evenly spaced numbers

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [17]:
a=np.array([1,2,3])
b=np.array([4,5,6])
print(a+b)
print(a*b)


[5 7 9]
[ 4 10 18]


In [18]:
print(a.mean())
print(a.max())
print(a.sum())

2.0
3
6


Reshape arrays


In [22]:
arr=np.arange(12)
print(arr.reshape(3,4))

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


MATRIX Multiplication

In [25]:
A=np.array([[1,2],[3,4]])
B=np.array([[5,6],[7,8]])
print(np.dot(A,B))


[[19 22]
 [43 50]]


In [26]:
print(A@B)

[[19 22]
 [43 50]]
